# Generated by Django 5.0.1 on 2024-02-05 23:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('second_last_name', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('municipality', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=200)),
                ('start_datetime', models.DateTimeField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EffectCard',
            fields=[
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='yugioh_tournament_app.card')),
                ('card_type', models.CharField(choices=[('S', 'Spell'), ('T', 'Trap')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='MonsterCard',
            fields=[
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='yugioh_tournament_app.card')),
                ('attack', models.PositiveIntegerField()),
                ('defense', models.PositiveIntegerField()),
                ('attribute', models.CharField(choices=[('DA', 'Dark'), ('DI', 'Divine'), ('E', 'Earth'), ('F', 'Fire'), ('L', 'Light'), ('WA', 'Water'), ('WI', 'Wind')], max_length=2)),
                ('level', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)])),
                ('is_effect', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CardInDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_type', models.CharField(choices=[('main_deck', 'main_deck'), ('side_deck', 'side_deck'), ('extra_deck', 'extra_deck')], max_length=10)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yugioh_tournament_app.card')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_name', models.CharField(max_length=200)),
                ('cards_in_deck', models.ManyToManyField(blank=True, through='yugioh_tournament_app.CardInDeck', to='yugioh_tournament_app.card')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yugioh_tournament_app.player')),
            ],
        ),
        migrations.AddField(
            model_name='cardindeck',
            name='deck',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yugioh_tournament_app.deck'),
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yugioh_tournament_app.deck')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yugioh_tournament_app.player')),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yugioh_tournament_app.tournament')),
            ],
        ),
        migrations.AddConstraint(
            model_name='monstercard',
            constraint=models.CheckConstraint(check=models.Q(('attribute__in', ['DA', 'DI', 'E', 'F', 'L', 'WA', 'WI'])), name='yugioh_tournament_app_monstercard_attribute_valid'),
        ),
    ]
