# Generated by Django 5.0.1 on 2024-01-24 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=200)),
                ('attack', models.PositiveIntegerField()),
                ('defense', models.PositiveIntegerField()),
                ('card_type', models.CharField(choices=[('M', 'Monster'), ('S', 'Spell'), ('T', 'Trap')], max_length=1)),
                ('attribute', models.CharField(choices=[('DA', 'Dark'), ('DI', 'Divine'), ('E', 'Earth'), ('F', 'Fire'), ('L', 'Light'), ('WA', 'Water'), ('WI', 'Wind')], max_length=2)),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)])),
                ('descrption', models.CharField(max_length=200)),
                ('is_effect', models.BooleanField()),
            ],
        ),
    ]
