# Generated by Django 5.0.1 on 2024-04-01 02:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_last_name', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('municipality', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_name', models.CharField(max_length=200)),
                ('main_deck', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(60)])),
                ('side_deck', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(15)])),
                ('extra_deck', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(15)])),
                ('archtype', models.CharField(default='Mixto', max_length=200)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='yugioh_tournament_app.player')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=200)),
                ('start_datetime', models.DateTimeField()),
                ('address', models.CharField(max_length=200)),
                ('champion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='yugioh_tournament_app.player')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner1', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(3)])),
                ('winner2', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(3)])),
                ('date', models.DateTimeField()),
                ('tournament_phase', models.CharField(max_length=200)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='was_player1', to='yugioh_tournament_app.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='was_player2', to='yugioh_tournament_app.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='duels', to='yugioh_tournament_app.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_aproved', models.BooleanField(default=False)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tournaments', to='yugioh_tournament_app.deck')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='yugioh_tournament_app.tournament')),
            ],
        ),
    ]
