# Generated by Django 5.0.1 on 2024-03-29 16:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yugioh_tournament_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duel',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='duel',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='duel',
            name='tournament',
        ),
        migrations.AlterField(
            model_name='tournamentparticipant',
            name='inscription_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 29, 12, 56, 49, 831254)),
        ),
        migrations.AddField(
            model_name='duel',
            name='player1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='was_player1', to='yugioh_tournament_app.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='duel',
            name='player2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='was_player2', to='yugioh_tournament_app.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='duel',
            name='tournament',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='duels', to='yugioh_tournament_app.tournament'),
            preserve_default=False,
        ),
    ]
