# Generated by Django 5.0.1 on 2024-01-24 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yugioh_tournament_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='descrption',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='card',
            name='level',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)]),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.CheckConstraint(check=models.Q(('attribute__in', ['DA', 'DI', 'E', 'F', 'L', 'WA', 'WI'])), name='yugioh_tournament_app_card_attribute_valid'),
        ),
    ]
