# Generated by Django 5.0.1 on 2024-02-05 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yugioh_tournament_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='owner',
            new_name='player',
        ),
    ]
