# Generated by Django 5.0.1 on 2024-03-02 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yugioh_tournament_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentparticipant',
            name='inscription_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 21, 20, 40, 271238)),
        ),
    ]
