# Generated by Django 5.0.1 on 2024-02-06 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yugioh_tournament_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentparticipant',
            name='player',
        ),
        migrations.AlterField(
            model_name='tournamentparticipant',
            name='inscription_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 12, 17, 29, 79375)),
        ),
    ]
