# Generated by Django 5.0.1 on 2024-02-06 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yugioh_tournament_app', '0002_remove_tournamentparticipant_player_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentparticipant',
            name='deck',
        ),
        migrations.AlterField(
            model_name='tournamentparticipant',
            name='inscription_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 12, 27, 31, 871207)),
        ),
        migrations.RemoveField(
            model_name='tournamentparticipant',
            name='tournament',
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='deck',
            field=models.ManyToManyField(to='yugioh_tournament_app.deck'),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='tournament',
            field=models.ManyToManyField(to='yugioh_tournament_app.tournament'),
        ),
    ]
