# Generated by Django 5.0.1 on 2024-01-30 02:25

import django.core.validators
import django.db.models.deletion
import yugioh_tournament_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yugioh_tournament_app', '0002_rename_descrption_card_description_alter_card_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_In_Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_type', models.CharField(choices=[('main_deck', 'main_deck'), ('side_deck', 'side_deck'), ('extra_deck', 'extra_deck')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EffectCard',
            fields=[
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='yugioh_tournament_app.card')),
                ('card_type', models.CharField(choices=[('S', 'Spell'), ('T', 'Trap')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='MonsterCard',
            fields=[
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='yugioh_tournament_app.card')),
                ('attack', models.PositiveIntegerField()),
                ('defense', models.PositiveIntegerField()),
                ('attribute', models.CharField(choices=[('DA', 'Dark'), ('DI', 'Divine'), ('E', 'Earth'), ('F', 'Fire'), ('L', 'Light'), ('WA', 'Water'), ('WI', 'Wind')], max_length=2)),
                ('level', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)])),
                ('is_effect', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('second_last_name', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('municipality', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15, validators=[yugioh_tournament_app.models.Player.is_valid_phonenumber])),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='card',
            name='yugioh_tournament_app_card_attribute_valid',
        ),
        migrations.RemoveField(
            model_name='card',
            name='attack',
        ),
        migrations.RemoveField(
            model_name='card',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='card',
            name='defense',
        ),
        migrations.RemoveField(
            model_name='card',
            name='is_effect',
        ),
        migrations.RemoveField(
            model_name='card',
            name='level',
        ),
        migrations.AlterField(
            model_name='card',
            name='card_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='card_in_deck',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yugioh_tournament_app.card'),
        ),
        migrations.AddField(
            model_name='deck',
            name='cards_in_deck',
            field=models.ManyToManyField(blank=True, through='yugioh_tournament_app.Card_In_Deck', to='yugioh_tournament_app.card'),
        ),
        migrations.AddField(
            model_name='card_in_deck',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yugioh_tournament_app.deck'),
        ),
        migrations.AddConstraint(
            model_name='monstercard',
            constraint=models.CheckConstraint(check=models.Q(('attribute__in', ['DA', 'DI', 'E', 'F', 'L', 'WA', 'WI'])), name='yugioh_tournament_app_monstercard_attribute_valid'),
        ),
    ]
