# Generated by Django 5.0.1 on 2024-03-02 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yugioh_tournament_app', '0002_alter_tournamentparticipant_inscription_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='tournamentparticipant',
            name='inscription_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 2, 4, 24, 18, 557049)),
        ),
    ]
