# Generated by Django 5.0.1 on 2024-01-30 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yugioh_tournament_app', '0003_card_in_deck_deck_effectcard_monstercard_player_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card_In_Deck',
            new_name='CardInDeck',
        ),
    ]
