# Generated by Django 5.0.1 on 2024-02-06 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yugioh_tournament_app', '0003_remove_tournamentparticipant_deck_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duel',
            name='loser',
        ),
        migrations.AddField(
            model_name='duel',
            name='player1',
            field=models.ManyToManyField(related_name='was_player1', to='yugioh_tournament_app.player'),
        ),
        migrations.AddField(
            model_name='duel',
            name='player2',
            field=models.ManyToManyField(related_name='was_player2', to='yugioh_tournament_app.player'),
        ),
        migrations.RemoveField(
            model_name='duel',
            name='tournament',
        ),
        migrations.AlterField(
            model_name='duel',
            name='winner',
            field=models.CharField(choices=[('player1', 'player1'), ('player2', 'player2'), ('tie', 'tie')], max_length=7),
        ),
        migrations.AlterField(
            model_name='tournamentparticipant',
            name='inscription_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 16, 21, 8, 930541)),
        ),
        migrations.AlterField(
            model_name='tournamentparticipant',
            name='tournament',
            field=models.ManyToManyField(related_name='participants', to='yugioh_tournament_app.tournament'),
        ),
        migrations.AddField(
            model_name='duel',
            name='tournament',
            field=models.ManyToManyField(related_name='duels', to='yugioh_tournament_app.tournament'),
        ),
    ]
